// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[...catchAll]" | "/[locale]/contact" | "/[locale]/projects" | "/[locale]/projects/[slug]" | "/[locale]/services" | "/[locale]/services/[slug]"
type AppRouteHandlerRoutes = "/api/leads" | "/api/terminal"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = "/" | "/contact/[[...path]]" | "/projects/[[...path]]" | "/services/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[...catchAll]": { "locale": string; "catchAll": string[]; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/projects": { "locale": string; }
  "/[locale]/projects/[slug]": { "locale": string; "slug": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/services/[slug]": { "locale": string; "slug": string; }
  "/api/leads": {}
  "/api/terminal": {}
  "/contact/[[...path]]": { "path"?: string[]; }
  "/projects/[[...path]]": { "path"?: string[]; }
  "/services/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": "projectModal"
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
