var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(mobile-preview)/mobile-preview/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10s0r9g._.js")
R.c("server/chunks/ssr/0asf_next_dist_0z-_wkg._.js")
R.c("server/chunks/ssr/0asf_next_dist_esm_build_templates_app-page_0~jsd5-.js")
R.c("server/chunks/ssr/[root-of-the-server]__06wh_lo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g69_a7._.js")
R.c("server/chunks/ssr/0asf_next_dist_client_components_0lqk0ua._.js")
R.c("server/chunks/ssr/0asf_next_dist_client_components_builtin_forbidden_0k3kef5.js")
R.c("server/chunks/ssr/0asf_next_dist_client_components_builtin_unauthorized_0refycm.js")
R.c("server/chunks/ssr/0asf_next_dist_client_components_builtin_global-error_0_k4hjf.js")
R.c("server/chunks/ssr/_12bg7jl._.js")
R.c("server/chunks/ssr/_0zkp-jy._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(mobile-preview)_mobile-preview_page_actions_0.0vc21.js")
R.m(78756)
module.exports=R.m(78756).exports
