var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__043oup.._.js")
R.c("server/chunks/ssr/0asf_next_dist_0z-_wkg._.js")
R.c("server/chunks/ssr/0asf_next_dist_esm_build_templates_app-page_0~st7~k.js")
R.c("server/chunks/ssr/[root-of-the-server]__06wh_lo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g69_a7._.js")
R.c("server/chunks/ssr/0asf_next_dist_client_components_builtin_global-error_0_k4hjf.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_0k77kol.js")
R.m(95449)
module.exports=R.m(95449).exports
